name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: julia-actions/CompatHelper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          compathelper_priv: ${{ secrets.DOCUMENTER_KEY }}
